### ISSUE TITLE
Add prefixes to conversion

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#14]
Output of CLI transformations should use prefixes:
```
bbo: <http://BPMNbasedOntology#>
stamp: <http://onto.fel.cvut.cz/ontologies/stamp/>
```

**Comment by grigobog** [comment]
Implemented in https://github.com/kbss-cvut/bpmn2stamp/releases/tag/0.05

**Comment by blcham** [comment]
Tested and works. @grigobog 

Although not sure why we need stamp: prefix in *-bpmn.ttl files, but it is acceptable. I assume it was easier to implement. E.g. `dozor-nad-provozovateli-letist-bpmn.ttl` contains `stamp:` prefix.
