### ISSUE TITLE
Make dozor-nad-provozovateli-letist transformation idempotent

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#29]
Try to make the transformation of  BPMN diagrams  `dozor-nad-provozovateli-letist` as idempotent as possible, if some parts are not possible to transform, let's discuss it here.

Related issue: #8 

To test the transformation do the following:
```
git clone https://github.com/kbss-cvut/bpmn2stamp
git clone https://github.com/kbss-cvut/bpmn-convertor-examples
cd bpmn-convertor-examples/processes/ucl
./bin/extract-bos.sh bos/dozor-nad-provozovateli-letist.bos
../../bin/build-bpmn2stamp.sh
./bin/process-bpmn.sh bpmn/dozor-nad-provozovateli-letist.bpmn
git diff dozor-nad-provozovateli-letist-bpmn.ttl
```

With these steps, you should get the following output of `git diff dozor-nad-provozovateli-letist-bpmn.ttl`:
![image](https://user-images.githubusercontent.com/3962237/168758730-e2eb1a2c-c564-47fa-a52d-95a2c96898eb.png)
 

A/C:
- the transformation is idempotent or we defined where are issues when we update diagram (described in this issue)
- make sure that actor-mapping is also transformed (i.e. mapping of actors to organization structure)

**Comment by blcham** [comment]
Current output on `git diff dozor-nad-provozovateli-letist-bpmn.ttl`:
![image](https://user-images.githubusercontent.com/3962237/168758730-e2eb1a2c-c564-47fa-a52d-95a2c96898eb.png)

**Comment by grigobog** [comment]
Now ids of such parts are generated from pool Id, action id (related to the boundary event) and one of the event property:

- TimeExpression will have the following id: <poolId>_<actionId>_<duration_in_milliseconds>
- TimerEventDefinition will have the following id: <poolId>_<actionId>_<event_id_from_bpmn>

This will make the convertion idempotent for such parts, described in #8, #23 and this issues.

**Comment by blcham** [comment]
After merging, I will test with my scripts (or you can do it in the pull request).
