### ISSUE TITLE
Duplicated entities from imported ontologies

### ISSUE THREAD

**Issue by grigobog** [kbss-cvut/bpmn2stamp#3]
There is an issue during saving instances with object properties referencing other instances from imported ontology. The referenced instances are persisted in the new ontology (with set cascade=PERSIST on has_role_part, otherwise error occurs).
E.g. ontology with id http://onto.fel.cvut.cz/ontologies/ucl/example/jednani-sag-bpmn has individuals with type model.bbo.model,Role with has_role_part object property referencing to another ontology (http://onto.fel.cvut.cz/ontologies/ucl/example/jednani-sag-organization-structure).
Steps to reproduce:
1. mvn clean
2. mvn package
3. mvn aspectj-maven-plugin:1.12.6:compile
4. run BpmnReaderServiceTest#mapAndWriteTest which should pass, but jednani-sag-bpmn.ttl contains duplicted referenced individuals from imported ontology (e.g. http://onto.fel.cvut.cz/ontologies/ucl/example/jednani-sag-organization-structure/ředitel_sekce).
Expected jednani-sag-bpmn.ttl contains no individuals from imported ontology (or at least containing only references).

**Comment by blcham** [comment]
@grigobog please update the issue as it was based on old source code
