### ISSUE TITLE
Automate package build

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#32]
Should be done using github actions.

A/C:
- package version should be based on version of  package in maven
- for now it is sufficient to replace when version of the package  does not change

**Comment by grigobog** [comment]
Created GitHub [action ](https://github.com/kbss-cvut/bpmn2stamp/blob/master/.github/workflows/maven.yml) to automate:
- building submodules (build clean)
- building fat jar (assembly:single)
- making GitHub release
This actions is triggered by pushing into master branch. Along with the new release a new tag is set to the latest commit (in master branch).
TODO: implement version extraction (e.g. from pom.xml) and using in action workflow. Now version "1.0-SNAPSHOT" is a constant.

**Comment by grigobog** [comment]
Implemented version extractionfrom pom.xml in action workflow.

**Comment by blcham** [comment]
> Implemented version extraction from pom.xml in action workflow.

FYI, you could use [#32] within the commit message so the commit would appear here automaticly.
