### ISSUE TITLE
Fix creation of pre-releases

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#39]
A/C:
- fix or justify why date of release is not updated
- sources are updated with same date as main jar artefacts

![image](https://user-images.githubusercontent.com/3962237/182150703-43a27ace-9e2e-4f1b-b316-1ab980584a42.png)

**Comment by grigobog** [comment]
It seems like if a new release is made using the same tag as in the previous - it is not considered as an actually new release, so release date is not updated. I see few options to fix this:
1. Add a step to build action to update version before the release (e.g. increment minor version number or add datetime)
2. Add datetime to the name of the release (even though release date will stay the same, it will not be that confusing).

For now I used option 2, so every new release will have date and time in the title.

**Comment by blcham** [comment]
@grigobog 

- choosing solution 2. is fine

- You wrote "For now I used option 2" ...   so I thought if I run again "[publish release](https://github.com/kbss-cvut/bpmn2stamp/blob/master/.github/workflows/publish-release.yml)"  action, it would work, but it did not, see dates here:
https://github.com/kbss-cvut/bpmn2stamp/releases/tag/1.0-SNAPSHOT

**Comment by grigobog** [comment]
Check why source codes are not updated.

**Comment by blcham** [comment]
This issue was not fully fixed but we have sufficient solution as demonstrated here:
![image](https://github.com/kbss-cvut/bpmn2stamp/assets/3962237/e5998697-d03a-4935-8fb2-3ed95aaaaea6)


Closing as the resolution of this issue is not priority now (it is non-trivial to solve).
