### ISSUE TITLE
Create diagram showing how converter maps BPMN elements to STAMP

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#46]
- links: [[1] Master thesis](https://dspace.cvut.cz/handle/10467/99110)  (most-likely `4.3.1.1
Organization structure to BBO mapping`)

- Final goal here is to provide documentation of the converter, where we want to be able to see what parts of STAMP structure are mapped. 

Steps:
- create diagram with BPMN schema (=BBO -- mark with different color our BBO concepts) and STAMP schema and mappings from [1]
- extend relevant STAMP schema/BPMN schema

**Comment by grigobog** [comment]
[bpmn_to_stamp_diagram PNG](https://drive.google.com/file/d/1p3o7VpZcsIH5CjnQGWngj36i1vd2e1yY/view)
[bpmn_to_stamp_diagram GRAPHML](https://drive.google.com/file/d/1h4uszjkQR9bcF29VNpp8eW_t5_KWsUR0/view)
(folder https://drive.google.com/drive/u/5/folders/14ESlEdir_1gFCiSrkLCikpr4DklvWpww)

**Comment by blcham** [comment]
@blcham see also related diagrams in [drive folder](https://drive.google.com/drive/u/5/folders/14ESlEdir_1gFCiSrkLCikpr4DklvWpww)

**Comment by grigobog** [comment]
TODO BG:

- describe conditions, when one element is mapped to another (use text on arrows)
- remove duplicities, such as is-role_partOf

**Comment by grigobog** [comment]
TODO:

- resolve comments in https://github.com/kbss-cvut/bpmn-convertor-examples/pull/33

**Comment by blcham** [comment]
1. Diagram and source code in graphml file into this repository (e.g. ./doc/)
2. Put some info and reference from main README.md to the added diagram.  
3. move diagram + source from google drive into sub-folder deprecated or remove.

It should be possible for new person to understand what is in the diagram.

**Comment by blcham** [comment]
@grigobog

**Comment by grigobog** [comment]
1. added to ./doc/ folder
2. added basic description of the diagram (including reference)
3. moved to [delete](https://drive.google.com/drive/u/8/folders/1veIemdjIwA24VAn_vHiJc27tqXcG57A-) drive folder

**Comment by blcham** [comment]
resolved.
