### ISSUE TITLE
Add support of the bbo-extension ontology

### ISSUE THREAD

**Issue by grigobog** [kbss-cvut/bpmn2stamp#47]
- [x] Replace updated BBO ontology by the original on
- [x] Add the new bbo-extension ontology (http://onto.fel.cvut.cz/ontologies/bbo)
- [x] Update prefixes and imports in convertor
- [x] Make changes from the comments in pull request https://github.com/kbss-cvut/bpmn-convertor-examples/pull/33
- [x] Test how it works on bpmn-convertor-examples/processes/ucl$ ./bin/process-bpmn.sh (can be done on next meeting)

**Comment by grigobog** [comment]
- made changes from the comments in pull request https://github.com/kbss-cvut/bpmn-convertor-examples/pull/33
- tested on bpmn-convertor-examples/processes/ucl using script bpmn-convertor-examples/processes/ucl$ ./bin/process-bpmn.sh: finished without errors, updated bpmn and pre-stamp output files are present in the latest commits in the bpmn-convertor-examples proejct

**Comment by blcham** [comment]
resolved
