### ISSUE TITLE
Converter does not convert some activities from a pool

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#49]
For more detail see https://github.com/kbss-cvut/stamp-viewer/issues/8#issuecomment-1463786174.

**Comment by blcham** [comment]
The goal would be to:
1) extend conversion to BBO with call activity
2) connect call activity to subprocess

**Comment by grigobog** [comment]
> The goal would be to do:
> 
> * [ ]  extend conversion to BBO with call activity-
> * [ ]  connect call activity to subprocess
> * [ ]  see point 3 in source ticket
> * STAMP should reflect structure of processes:
>   
>   1. [ ]  swim-lane (bbo:process, stamp:controlled-process)  -- (bbo:has-flow-element, stamp:has-structural-element-part)  --> user-task (bbo:process, stamp:process)
>   2. [ ]  call activity (bbo:call-activity,  stamp:controlled-process, stamp:process)  -- (bbo:has_calledElement, stamp:has-structural-element-part) --> subprocess user-task (bbo:process, stamp:process)

All items are resolved (see the latest commits). After testing and merging to master this issue can be closed.

**Comment by blcham** [comment]
It has been merged and deployed.

**Comment by blcham** [comment]
@grigobog BTW, here is what has changed in dozor dataset -- https://github.com/kbss-cvut/bpmn-convertor-examples/pull/43
